'use client';

import { useState } from 'react';
import { FileText, Printer, CheckCircle2 } from 'lucide-react';

export default function StaffReportsPage() {
  const [selectedBatch, setSelectedBatch] = useState('Batch 12 - Signals & Systems');

  const studentMarks = [
    { id: '24ECE101', name: 'Arjun Reddy', internal: 38, external: 55, total: 93, grade: 'O' },
    { id: '24ECE112', name: 'Karthik Iyer', internal: 25, external: 42, total: 67, grade: 'B+' },
    { id: '24CSE205', name: 'Priya Sharma', internal: 35, external: 50, total: 85, grade: 'A+' },
  ];

  // 🖨️ 4B. NATIVE PDF/PRINT GENERATOR
  const triggerPDFExport = () => {
    window.print();
  };

  return (
    <div className="space-y-8 max-w-6xl mx-auto animate-in fade-in duration-500">
      
      {/* ⚠️ Anything with "print:hidden" completely vanishes when exporting to PDF! */}
      <div className="flex justify-between items-center print:hidden">
        <div>
          <h1 className="text-3xl font-bold text-slate-900 dark:text-white">Generate Reports</h1>
          <p className="text-slate-500 dark:text-slate-400 mt-1">Review class performance and export official grading sheets.</p>
        </div>
        
        <button onClick={triggerPDFExport} className="px-6 py-2 bg-indigo-600 text-white rounded-lg font-medium hover:bg-indigo-500 transition-colors shadow-sm flex items-center">
          <Printer className="w-4 h-4 mr-2" /> Export to PDF
        </button>
      </div>

      {/* This is the ONLY thing that will show up on the generated PDF document! */}
      <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden print:border-none print:shadow-none">
        
        {/* Official Header for the PDF only */}
        <div className="hidden print:block text-center pb-8 border-b-2 border-black mb-8">
           <h1 className="text-3xl font-black text-black">APEXGRADE UNIVERSITY</h1>
           <p className="text-lg text-black font-bold mt-2">Official Marks Ledger - {selectedBatch}</p>
           <p className="text-sm text-gray-600 mt-1">Generated by Faculty Portal</p>
        </div>

        <div className="p-4 bg-slate-50/50 dark:bg-slate-950/50 border-b border-slate-200 dark:border-slate-800 flex justify-between items-center print:hidden">
          <h2 className="text-sm font-bold text-slate-700 dark:text-slate-300 flex items-center">
            <FileText className="w-4 h-4 mr-2 text-indigo-500" /> Marks Ledger Preview
          </h2>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm whitespace-nowrap print:text-black">
            <thead className="bg-slate-50 dark:bg-slate-950/50 text-slate-500 dark:text-slate-400 border-b border-slate-200 dark:border-slate-800 print:bg-gray-100 print:text-black">
              <tr>
                <th className="px-6 py-4 font-medium">Student Profile</th>
                <th className="px-6 py-4 font-medium text-center">Internal (40)</th>
                <th className="px-6 py-4 font-medium text-center">External (60)</th>
                <th className="px-6 py-4 font-medium text-center">Total (100)</th>
                <th className="px-6 py-4 font-medium text-center">Final Grade</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 dark:divide-slate-800/50 text-slate-700 dark:text-slate-300 print:text-black">
              {studentMarks.map((student) => (
                <tr key={student.id} className="hover:bg-slate-50/50 dark:hover:bg-slate-800/20 print:border-b print:border-gray-300">
                  <td className="px-6 py-4">
                    <div className="font-bold">{student.name}</div>
                    <div className="text-xs opacity-70">{student.id}</div>
                  </td>
                  <td className="px-6 py-4 text-center">{student.internal}</td>
                  <td className="px-6 py-4 text-center">{student.external}</td>
                  <td className="px-6 py-4 text-center font-bold">{student.total}</td>
                  <td className="px-6 py-4 text-center font-bold">{student.grade}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}